# Generated by Django 5.2.4 on 2025-08-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pagina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
