# Generated by Django 5.2.4 on 2025-08-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_bio_alter_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/6858504.jpg', null=True, upload_to='avatars/'),
        ),
    ]
